/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ControladorCliente;
import Modelo.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author monto
 */
public class FrmBuscarCliente extends javax.swing.JFrame {
    private ControladorCliente controladorCliente;
private java.awt.Window ventanaAnterior;
private DefaultTableModel modeloTabla;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarCliente.class.getName());

    FrmBuscarCliente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
private void agregarClienteTabla(Cliente cliente) {

    String nombreCompleto = cliente.getNombreCompleto();

    String nombre = nombreCompleto;
    String apellido = "";

    String[] partes = nombreCompleto.split(" ", 2);

    if (partes.length > 0) {
        nombre = partes[0];
    }

    if (partes.length > 1) {
        apellido = partes[1];
    }

    modeloTabla.addRow(new Object[]{
        cliente.getId(),
        nombre,
        apellido,
        cliente.getTelefono(),
        cliente.getCorreoElectronico()
    });
}
    /**
     * Creates new form FrmBuscarCliente
     */
public FrmBuscarCliente(ControladorCliente controladorCliente,
                        java.awt.Window ventanaAnterior) {

    initComponents();

    this.controladorCliente = controladorCliente;
    this.ventanaAnterior = ventanaAnterior;

    modeloTabla = new DefaultTableModel(
        new Object[]{
            "Cédula",
            "Nombre",
            "Apellido",
            "Teléfono",
            "Correo"
        }, 0
    );

    jTable1.setModel(modeloTabla);

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btntext = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel1.setText("Buscar clientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Buscar por :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Nombre", "Teléfono", "Correo" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        btntext.setText("jTextField1");
        btntext.addActionListener(this::btntextActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(this::btnSeleccionarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btntext, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnBuscar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnSeleccionar)
                        .addGap(58, 58, 58)
                        .addComponent(btnLimpiar)
                        .addGap(40, 40, 40)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
         String criterio = jComboBox2.getSelectedItem().toString();

    btntext.setText("");
    btntext.requestFocus();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btntextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntextActionPerformed
  String texto = btntext.getText().trim();

    if (texto.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingrese un dato para buscar.",
                "Buscar cliente",
                JOptionPane.WARNING_MESSAGE
        );

        btntext.requestFocus();
        return;
    }

    btnBuscar.doClick();
    }//GEN-LAST:event_btntextActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String texto = btntext.getText().trim();

    if (texto.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingrese un dato para buscar.",
                "Buscar cliente",
                JOptionPane.WARNING_MESSAGE
        );

        btntext.requestFocus();
        return;
    }

    String criterio = jComboBox2.getSelectedItem().toString();

    modeloTabla.setRowCount(0);

    if (criterio.equals("Cédula")) {

        Cliente cliente = controladorCliente.buscarCliente(texto);

        if (cliente != null) {

            agregarClienteTabla(cliente);

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró ningún cliente con esa cédula.",
                    "Buscar cliente",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }

    } else {

        ArrayList<Cliente> clientes =
                controladorCliente.listarClientes();

        boolean encontrado = false;

        for (Cliente cliente : clientes) {

            String dato = "";

            if (criterio.equals("Nombre")) {
                dato = cliente.getNombreCompleto();
            }

            if (criterio.equals("Teléfono")) {
                dato = cliente.getTelefono();
            }

            if (criterio.equals("Correo")) {
                dato = cliente.getCorreoElectronico();
            }

            if (dato.toLowerCase().contains(texto.toLowerCase())) {

                agregarClienteTabla(cliente);
                encontrado = true;
            }
        }

        if (!encontrado) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontraron clientes.",
                    "Buscar cliente",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
    btnBuscar.setText("");
    btnBuscar.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
       

    int fila = jTable1.getSelectedRow();

    if (fila == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un cliente de la tabla.",
                "Seleccionar cliente",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String cedula =
            jTable1.getValueAt(fila, 0).toString();

    Cliente cliente =
            controladorCliente.buscarCliente(cedula);

    if (cliente == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el cliente.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    JOptionPane.showMessageDialog(
            this,
            "Cliente seleccionado:\n\n"
            + "Cédula: " + cliente.getId()
            + "\nNombre: " + cliente.getNombreCompleto()
            + "\nTeléfono: " + cliente.getTelefono()
            + "\nCorreo: " + cliente.getCorreoElectronico(),
            "Cliente seleccionado",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmBuscarCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField btntext;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
