/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import Modelo.Espacio;
import controlador.ControladorEspacio;
import Modelo.TipoEspacio;
import Modelo.excepciones.EspacioDuplicadoException;
import controlador.ControladorPrincipal;
import javax.swing.JOptionPane;
import Modelo.excepciones.EspacioOcupadoException;
/**
 *
 * @author isaac
 */
public class VentanaEspacio extends javax.swing.JFrame {
    
    private ControladorEspacio controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEspacio.class.getName());

    /**
     * Creates new form VentanaEspacio
     */
    public VentanaEspacio(ControladorEspacio controlador) {
        initComponents();
        this.controlador= controlador;
    }
    
    public void cargarEspacio(Espacio espacio) {
        txtNumero.setText(espacio.getNumeroEspacio());
        cbTipo.setSelectedItem(espacio.getTipo().toString());
        txtTamano.setText(String.valueOf(espacio.getTamanoM2()));
        txtPrecio.setText(String.valueOf(espacio.getPrecioMensual()));
        txtDisponibilidad.setText(espacio.getEstado().toString());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTamano = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDisponibilidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Espacio");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setText("ADMINISTRAR ESPACIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Numero Espacio:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1);

        txtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtNumero);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de Espacio:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel2);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        cbTipo.addActionListener(this::cbTipoActionPerformed);
        jPanel2.add(cbTipo);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tamaño:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel3);

        txtTamano.setEditable(false);
        txtTamano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtTamano);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Precio mensual:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel4);

        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtPrecio);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Disponibilidad:");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel5);

        txtDisponibilidad.setEditable(false);
        txtDisponibilidad.setText("Disponible");
        txtDisponibilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtDisponibilidad);

        jPanel3.setLayout(new java.awt.GridLayout(1, 5, 10, 10));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        jPanel3.add(btnAgregar);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        jPanel3.add(btnActualizar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel3.add(btnEliminar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel3.add(btnBuscar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel3.add(btnLimpiar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String numero = txtNumero.getText().trim();
        
        if(numero.isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar el número del espacio.");
        return;
        }
        
        double precio;
        try{
        precio= Double.parseDouble(txtPrecio.getText());

        if(precio<=0){
            JOptionPane.showMessageDialog(this, "El precio debe ser mayor que cero.");
            return;
        }

        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.");
            return;
        }

        String tipoSeleccionado= cbTipo.getSelectedItem().toString();

        TipoEspacio tipo= TipoEspacio.Pequeño;

        if(tipoSeleccionado.equals("Mediano")){
            tipo= TipoEspacio.Mediano;
        }else if(tipoSeleccionado.equals("Grande")) {
            tipo= TipoEspacio.Grande;
        }

        double tamano= tipo.getTamanoM2();
        boolean actualizado= controlador.actualizarEspacio(numero, tipo, tamano, precio);

        if(actualizado){
            JOptionPane.showMessageDialog(this, "Espacio actualizado correctamente.");
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró el espacio.");
            }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNumero.setText("");
        cbTipo.setSelectedIndex(0);
        txtTamano.setText(String.valueOf(TipoEspacio.Pequeño.getTamanoM2()));
        txtPrecio.setText(String.valueOf(TipoEspacio.Pequeño.getPrecioDefecto()));
        txtDisponibilidad.setText("Disponible");
        txtNumero.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        
        String tipo= cbTipo.getSelectedItem().toString();
        if(tipo.equals("Pequeño")){
            txtTamano.setText(String.valueOf(TipoEspacio.Pequeño.getTamanoM2()));
            txtPrecio.setText(String.valueOf(TipoEspacio.Pequeño.getPrecioDefecto()));
        }else if(tipo.equals("Mediano")){
            txtTamano.setText(String.valueOf(TipoEspacio.Mediano.getTamanoM2()));
            txtPrecio.setText(String.valueOf(TipoEspacio.Mediano.getPrecioDefecto()));
        }else if(tipo.equals("Grande")){
            txtTamano.setText(String.valueOf(TipoEspacio.Grande.getTamanoM2()));
            txtPrecio.setText(String.valueOf(TipoEspacio.Grande.getPrecioDefecto()));
        }    
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String numero = txtNumero.getText().trim();
        
        if(numero.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el número del espacio.");
            return;
        }

        String tipoSeleccionado= cbTipo.getSelectedItem().toString();

        TipoEspacio tipo= TipoEspacio.Pequeño;

        if(tipoSeleccionado.equals("Mediano")){
        tipo= TipoEspacio.Mediano;
        }else if(tipoSeleccionado.equals("Grande")){
        tipo= TipoEspacio.Grande;
        }

        try{

        controlador.agregarEspacio(numero, tipo);
        JOptionPane.showMessageDialog(this, "Espacio agregado correctamente.");
    }catch(EspacioDuplicadoException ex){
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String numero = txtNumero.getText().trim();

        if(numero.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el número del espacio.");
            return;
        }

        try{

        boolean eliminado = controlador.eliminarEspacio(numero);

        if(eliminado){
            JOptionPane.showMessageDialog(this, "Espacio eliminado correctamente.");
        }else{
            JOptionPane.showMessageDialog(this, "No se encontró el espacio.");
        }

        }catch(EspacioOcupadoException ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar el espacio porque está ocupado.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        VentanaBuscarEspacio ventana=new VentanaBuscarEspacio(controlador, this);

        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDisponibilidad;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamano;
    // End of variables declaration//GEN-END:variables
}
