/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ControladorEspacio;
import Modelo.Espacio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author isaac
 */
public class VentanaBuscarEspacio extends javax.swing.JFrame {
    
    private ControladorEspacio controlador;
    private VentanaEspacio ventanaEspacio;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBuscarEspacio.class.getName());

    /**
     * Creates new form VentanaBuscarEspacio
     */
    public VentanaBuscarEspacio(ControladorEspacio controlador, VentanaEspacio ventanaEspacio) {
        initComponents();
        this.controlador = controlador;
        this.ventanaEspacio= ventanaEspacio;
        cargarTabla();
    }
    
    private void cargarTabla(){
    DefaultTableModel modelo =(DefaultTableModel) tblEspacios.getModel();

    modelo.setRowCount(0);

    for (Espacio espacio: controlador.listarEspacios()){
        modelo.addRow(new Object[]{
            espacio.getNumeroEspacio(),
            espacio.getTipo(),
            espacio.getTamanoM2(),
            espacio.getPrecioMensual(),
            espacio.getEstado()
        });
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTipoBuscar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioMax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbDisponibilidadBuscar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspacios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setText("BUSCAR ESPACIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(198, 198, 198))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(4, 4, 10, 10));

        jLabel1.setText("Numero:");
        jPanel5.add(jLabel1);

        txtNumeroBuscar.addActionListener(this::txtNumeroBuscarActionPerformed);
        jPanel5.add(txtNumeroBuscar);

        jLabel2.setText("Tipo:");
        jPanel5.add(jLabel2);

        cbTipoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pequeño", "Mediano", "Grande" }));
        jPanel5.add(cbTipoBuscar);

        jLabel3.setText("Precio Maximo:");
        jPanel5.add(jLabel3);

        txtPrecioMax.addActionListener(this::txtPrecioMaxActionPerformed);
        jPanel5.add(txtPrecioMax);

        jLabel4.setText("Precio Minimo:");
        jPanel5.add(jLabel4);

        txtPrecioMin.addActionListener(this::txtPrecioMinActionPerformed);
        jPanel5.add(txtPrecioMin);

        jLabel5.setText("Disponibilidad:");
        jPanel5.add(jLabel5);

        cbDisponibilidadBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Disponible", "Ocupado" }));
        jPanel5.add(cbDisponibilidadBuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel5.add(btnBuscar);
        jPanel5.add(jLabel6);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        jPanel5.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel5.add(btnCancelar);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        tblEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero", "Tipo", "Tamaño", "Precio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEspacios);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroBuscarActionPerformed

    private void txtPrecioMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMaxActionPerformed

    private void txtPrecioMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMinActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int fila= tblEspacios.getSelectedRow();

        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un espacio.");
            return;
        }

        String numero= tblEspacios.getValueAt(fila, 0).toString();
        Espacio espacio= controlador.buscarEspacio(numero);
        ventanaEspacio.cargarEspacio(espacio);
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String numero= txtNumeroBuscar.getText().trim();
        String tipo= cbTipoBuscar.getSelectedItem().toString();
        String disponibilidad= cbDisponibilidadBuscar.getSelectedItem().toString();

        double precioMin= 0;
        double precioMax= Double.MAX_VALUE;

        try{

            if(!txtPrecioMin.getText().trim().isEmpty()){
                precioMin= Double.parseDouble(txtPrecioMin.getText().trim());
            }

            if(!txtPrecioMax.getText().trim().isEmpty()){
                precioMax = Double.parseDouble(txtPrecioMax.getText().trim());
            }

        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Los precios deben ser números válidos.");
            return;
        }

        DefaultTableModel modelo=(DefaultTableModel)tblEspacios.getModel();

        modelo.setRowCount(0);

        for(Espacio espacio : controlador.listarEspacios()){
            boolean cumple = true;

            if(!numero.isEmpty()&& !espacio.getNumeroEspacio().equals(numero)){
                cumple=false;
            }

            if(!tipo.equals("Todos")&& !espacio.getTipo().toString().equals(tipo)) {
                cumple= false;
            }

            if(!disponibilidad.equals("Todos")&& !espacio.getEstado().toString().equals(disponibilidad)) {
                cumple=false;
            }

            if(espacio.getPrecioMensual()<precioMin|| espacio.getPrecioMensual()>precioMax){
                cumple = false;
            }

            if(cumple){
                modelo.addRow(new Object[]{
                    espacio.getNumeroEspacio(),
                    espacio.getTipo(),
                    espacio.getTamanoM2(),
                    espacio.getPrecioMensual(),
                    espacio.getEstado()
                });
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbDisponibilidadBuscar;
    private javax.swing.JComboBox<String> cbTipoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEspacios;
    private javax.swing.JTextField txtNumeroBuscar;
    private javax.swing.JTextField txtPrecioMax;
    private javax.swing.JTextField txtPrecioMin;
    // End of variables declaration//GEN-END:variables
}
